sudo: false
language: "perl"
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
matrix:
    allow_failures:
        - perl: 'blead'
        - perl: '5.8'
    fast_finish: true

before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    # optional dependencies
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla Pod::Weaver::Section::Support
    - cpanm --quiet --notest Sparrow
    - sparrow plg install perl-file-dir-dumper-smoke

install:
    - "(cd File-Dir-Dumper/ && dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest)"
    - "(cd File-Dir-Dumper/ && dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose)"
script:
    - "cd File-Dir-Dumper/ && dzil smoke --release --author"
    - "export PERL5LIB=$PWD/lib && sparrow plg run perl-file-dir-dumper-smoke"
